
name: Continuous Integration Testing
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  microprofile-jdt-ext-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Run the Maven verify phase
        working-directory: "microprofile.jdt"
        run: mvn --batch-mode --update-snapshots verify
  microprofile-ls-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Run the Maven verify phase
        working-directory: "microprofile.ls/org.eclipse.lsp4mp.ls"
        run: mvn --batch-mode --update-snapshots verify
